# Generated by Django 3.0.5 on 2020-04-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='content',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
